### ISSUE TITLE
<error> getBalance call failed

### ISSUE THREAD

**Issue by burimaliu** [eXtremal-ik7/pool_frontend_zcash#8]
I am seeing this on console `<error> getBalance call failed` is this normal behavior  ?

**Comment by eXtremal-ik7** [comment]
If timeout - normal, if you see that every 3 minutes - not normal

**Comment by burimaliu** [comment]
I see it all the time, maybe every 2 - 3 mins.

**Comment by eXtremal-ik7** [comment]
Ok, check pool_zaddr and pool_taddr addresses in your pool config. Are these addresses really exists in your pool wallet.dat file ?

**Comment by ghost** [comment]
Hi, eXtremal-ik7
       Is there  a mistakethe in function "ioGetBlockByHash" file poolcore/src/poolcommon/poolapi.cpp?
why the parameter is "getBalance"?

std::unique_ptr<GetBlockByHashResultT> ioGetBlockByHash(p2pNode _client,
                      std::vectorstd::string &hashes)
{
  const size_t size = hashes.size()_4096;
  std::unique_ptr<uint8_t[]> buffer(new uint8_t[size]);
  flatbuffers::FlatBufferBuilder fbb;  
  auto reqOffset = CreateGetBlockByHashReq(fbb, fbb.CreateVectorOfStrings(hashes));
  fbb.Finish(CreateP2PMessage(fbb, FunctionId_GetBlockByHash, Data_GetBlockByHashReq, reqOffset.Union()));

  auto result = request<GetBlockByHashResult>(client, fbb, 3000000, "getBalance", buffer.get(), size);
  if (result) {
    return std::unique_ptr<GetBlockByHashResultT>(result->UnPack());
  } else {
    return 0;
  }  
}

**Comment by nginnever** [comment]
I see `<error> getBalance call failed` every few seconds. I think that my addresses in the config exist in my wallet.dat since i generated them normally during setup.

Is it possible that since there have been no transactions to these addresses yet they do not register with and zcashd api calls?

EDIT:

I fell asleep and woke up to find our pool had mined a block and now the error message is gone. Which makes me think again that the call can't be made util some tx happens to put it on chain and out of the keypool.

Cheers

**Comment by nginnever** [comment]
Changing the line you mention above to ``getBlockByHash`` to see if can complete that call. I can confirm that ``auto result = request(client, fbb, 3000000, "getBalance", buffer.get(), size);`` is the call that is throwing my error.

Finding a block still resolves this error. I would like to find out why however.

**Comment by ddobreff** [comment]
Send 0.001 ZEC to t/Z address and there won't be any error like that. Empty wallet returns null value.

**Comment by eXtremal-ik7** [comment]
It was 'getBlockByHash' problem, fixed
